### PR TITLE
Forward compatibility with react/event-loop 1.0 and 0.5 while still supporting 0.4

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Comment by mbonneau** [comment]
@WyriHaximus Thanks for keeping us up-to-date!

**Comment by WyriHaximus** [comment]
@mbonneau no problem 👍 !

**Comment by WyriHaximus** [comment]
Any change you could tag a release with this PR in it?

**Comment by WyriHaximus** [comment]
Thank you! Much appreciated 👍 !

**Comment by davidwdan** [comment]
No problem

**Pull request merged**
